spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  jooq:
    sql-dialect: POSTGRES

